name: Unit Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
  UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  CLOUDFRONT_URL: ${{ secrets.CLOUDFRONT_URL }}
  REGION: ${{ secrets.REGION }}
  DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
  DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY }}
  NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
  NEXTAUTH_URL: ${{ secrets.NEXTAUTH_URL }}

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository 🫠
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          cache: "pnpm"
      - name: Install modules
        run: pnpm install --frozen-lockfile
      - run: pnpm test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository 🫠
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          cache: "pnpm"
      - name: Install modules
        run: pnpm install --frozen-lockfile
      - run: pnpm build
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository 🫠
        uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          cache: "pnpm"
      - name: Install modules
        run: pnpm install --frozen-lockfile
      - name: Check formatting with Prettier
        run: npm run format:check
